OD-234 [Feature] Show chat in full screen on mobile devices.
Fliplet/fliplet-widget-chat pull request #106
Opened 2020-11-12 13:28 UTC by YaroslavOvdii

@sofiiakvasnevska 

## Issue
https://weboo.atlassian.net/browse/OD-234

## Description
Show chat in full screen on mobile devices.

## Screenshots/screencasts
https://share.getcloudapp.com/v1uxwk4R

## Backward compatibility
This change is fully backward compatible.

## Reviewers
@upplabs-alex-levchenko

2020-11-12 14:45 UTC, squallstar commented
@tonytlwu @hcarneiro can you confirm you're okay with the implementation by @YaroslavOvdii?

I don't like it because
1. if the top menu is not 40px tall then there's an issue
2. if there is no top menu then the UI will break

What do you think? Can you recommend any viable way to implement this?

2020-11-12 14:56 UTC, tonytlwu requested changes

2020-11-12 14:56 UTC, tonytlwu commented on css/chat.css
> +  top: -40px;
[@squallstar's concern](https://github.com/Fliplet/fliplet-widget-chat/pull/106#issuecomment-726122018) is valid.

`body` has the classes `fl-with-top-menu` or `fl-with-bottom-menu` depending on whether there's a menu at the top or bottom. You can make use of this information if you want to assess the presence of top and bottom menus.

In addition, avoid using specific pixel numbers that rely on the design/appearance of other components. `position: fixed`, for example, would be a pretty straightforward method to anchor something to the viewport using CSS.

2020-11-18 09:39 UTC, YaroslavOvdii commented
Created new [PR ](https://github.com/Fliplet/fliplet-widget-chat/pull/107) with a new solution

2020-11-18 09:39 UTC, closed without merging