XOR-305 [FEAT] Ensure File encrypted in chat and its access restricted from file manager
Fliplet/fliplet-widget-chat pull request #124
Opened 2022-08-25 08:43 UTC by anerib

### Product areas affected

Chat Widget - Attach the encryption key when file is send in chat message

### What does this PR do?

This PR has added private encryption key to each file which is send in chat message

### JIRA ticket

[XOR-305](https://weboo.atlassian.net/browse/XOR-305)

### Result
Added `hasPrivateEncryptionKey` flag and no private key in metadata returns to the user
![XOR-305](https://user-images.githubusercontent.com/101858104/186617754-577063fc-4503-488e-aedf-217a38aa454e.PNG)

https://user-images.githubusercontent.com/101858104/186617889-5aea8cae-9761-4a41-9aef-50c49991eeac.mp4

### Checklist
None

### Deployment instructions
None

### Author concerns
None

2022-08-25 09:08 UTC, yogeshmsharma-xoriant approved these changes
looks ok to me

2022-08-25 09:29 UTC, anerib commented on widget.json
> +      "vendor/purify.min.js",
eslint picked up the changes on saving the file automatically.

2022-08-26 10:25 UTC, tonytlwu requested changes

2022-08-26 10:25 UTC, tonytlwu commented on js/build.js
> +        hasMediaFileWithPrivateEncryptionKey: files ? true : false,
```suggestion
        hasMediaFileWithPrivateEncryptionKey: !!files,
```

2022-08-30 17:22 UTC, tonytlwu approved these changes

2022-09-02 12:47 UTC, merged